Generación de pruebas basicas de API .Se utiliza consola Virtual Studio Code para codigo en lenguaje python usando pytest
Comando para ejecutar las pruebas  como: python -m pytest -v (correr test detallado) 
y python -m pytest --html=report.html --self-contained-html (correr test obteniendo reporte html)

en consola Virtual Studio se ejecutaron por makers de esta forma 
python -m pytest -m get -v
python -m pytest -m post -v
python -m pytest -m delete -v
